favorite_fruits = "strawberries", "raspberries","kiwis"
if "bananas" in favorite_fruits:
    print("You really like bananas!")
if "apples" in favorite_fruits:
    print("You really like apples!")
if "strawberries" in favorite_fruits:
    print("You really like strawberries!")
if "raspberries" in favorite_fruits:
    print("You really like raspberries")
if "kiwis" in favorite_fruits:
    print("You really like kiwis!")